apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-processing

resources:
- serviceaccount.yaml
- config.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- minio-deployment.yaml
- spark-cluster.yaml

commonLabels:
  app.kubernetes.io/name: data-processing
  app.kubernetes.io/managed-by: kustomize
